### ISSUE TITLE
HTML support?

### ISSUE THREAD

**Issue by sztojkatamas** [kissrichard/tinyloadtest#2]
So it works for a JSON, but still not good for web pages

python apitester.py 10 "https://maps.owm.io/weather/cities/1/1/1.geojson?appid=b1b15e88fa797225412429c1c50c122a1"

python apitester.py 10 "http://www.sg.hu"
FETCHING URL >>> 'http://www.sg.hu'
ERROR: Response contains invalid JSON, encoding of the response failed...
 script exits

**Comment by bitmill** [comment]
**In the last update you can find the followings:**
- JSON specificity removed, now the script can handle all kind of URL's/Resources
- URL validation added (new external lib dependency, please follow the [readme](https://github.com/bitmill/apitester/blob/master/README.md) !)
- Brand new logic behind counting the nr. of responses/sec.
- "ConnectionError" handling added
- Minor code refactoring
